#!/usr/bin/env bash
# 0. Transfer a file to your server
path="$1"
ip="$2"
username="$3"
ssh_key="$4"

if [ $# -eq 4 ]
then
    scp -i ${ssh_key} ${path} ${username}@${ip}
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
