#!/usr/bin/env bash
# Pings an IP address passed as an argument.

if [ $# -eq 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

for i in {1..5}
do
    ping "$1"
done
