#!/usr/bin/env bash
# Displays numbers from 1 to 100 with conditions

for i in {1..100}
do
    if (( i % 3 == 0 ))
    then
        if (( i % 5 == 0 ))
        then
            echo "FizzBuzz"
        else
            echo "Fizz"
        fi
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done
